# Generated by Django 4.1.1 on 2022-09-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=200, unique=True)),
                ('blogcontent', models.TextField()),
                ('blogauthor', models.CharField(max_length=200)),
                ('postdate', models.DateField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
