# Generated by Django 4.1.1 on 2022-09-27 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='postdate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 27, 12, 12, 18, 989259, tzinfo=datetime.timezone.utc)),
        ),
    ]
