# Generated by Django 4.1.1 on 2022-09-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogdb_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='postdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
