# Generated by Django 4.1.1 on 2022-09-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogdb_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
