# Generated by Django 4.1.1 on 2022-09-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogdb_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
