# Generated by Django 4.1.1 on 2022-10-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0003_alter_profilemodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
